name: tugasku
description: Aplikasi pengingat tugas dan deadline untuk pelajar.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  google_sign_in: ^7.0.0
  flutter_local_notifications: ^22.3.1
  timezone: ^0.11.1
  flutter_timezone: ^5.1.1
  file_picker: ^13.1.0
  image_picker: ^1.2.4
  path_provider: ^2.1.6
  open_filex: ^4.7.0
  intl: ^0.20.3
  http: ^1.6.0
  cryptography: ^2.9.0
  flutter_secure_storage: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
